/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { AuthResponseTokenType } from './authResponseTokenType';
import type { AuthResponseUser } from './authResponseUser';

export interface AuthResponse {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  token_type?: AuthResponseTokenType;
  user?: AuthResponseUser;
}
