/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export type AuthResponseTokenType = typeof AuthResponseTokenType[keyof typeof AuthResponseTokenType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthResponseTokenType = {
  Bearer: 'Bearer',
} as const;
