/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { AuthResponseUserPhone } from './authResponseUserPhone';
import type { AuthResponseUserProfileImage } from './authResponseUserProfileImage';

export type AuthResponseUser = {
  id?: string;
  email?: string;
  phone?: AuthResponseUserPhone;
  username?: string;
  profile_image?: AuthResponseUserProfileImage;
  currency?: string;
  language?: string;
  email_verified?: boolean;
  created_at?: string;
  updated_at?: string;
};
