/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { GetAuthSessions200SessionsItemDeviceName } from './getAuthSessions200SessionsItemDeviceName';
import type { GetAuthSessions200SessionsItemIpAddress } from './getAuthSessions200SessionsItemIpAddress';
import type { GetAuthSessions200SessionsItemUserAgent } from './getAuthSessions200SessionsItemUserAgent';

export type GetAuthSessions200SessionsItem = {
  id?: string;
  user_id?: string;
  device_name?: GetAuthSessions200SessionsItemDeviceName;
  ip_address?: GetAuthSessions200SessionsItemIpAddress;
  user_agent?: GetAuthSessions200SessionsItemUserAgent;
  expires_at?: string;
  created_at?: string;
};
