/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { GetAuthSessionsSessionId200SessionDeviceName } from './getAuthSessionsSessionId200SessionDeviceName';
import type { GetAuthSessionsSessionId200SessionIpAddress } from './getAuthSessionsSessionId200SessionIpAddress';
import type { GetAuthSessionsSessionId200SessionUserAgent } from './getAuthSessionsSessionId200SessionUserAgent';

export type GetAuthSessionsSessionId200Session = {
  id?: string;
  user_id?: string;
  device_name?: GetAuthSessionsSessionId200SessionDeviceName;
  ip_address?: GetAuthSessionsSessionId200SessionIpAddress;
  user_agent?: GetAuthSessionsSessionId200SessionUserAgent;
  expires_at?: string;
  created_at?: string;
};
