/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { GetAuthSessionsSessionId200Session } from './getAuthSessionsSessionId200Session';

export type GetAuthSessionsSessionId200 = {
  session?: GetAuthSessionsSessionId200Session;
};
