/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export interface LoginBody {
  email: string;
  /** @minLength 1 */
  password: string;
  /** @maxLength 255 */
  device_name?: string;
}
