/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export type PostAuthRefresh200TokenType = typeof PostAuthRefresh200TokenType[keyof typeof PostAuthRefresh200TokenType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthRefresh200TokenType = {
  Bearer: 'Bearer',
} as const;
