/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export type PostAuthRegister201TokenType = typeof PostAuthRegister201TokenType[keyof typeof PostAuthRegister201TokenType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthRegister201TokenType = {
  Bearer: 'Bearer',
} as const;
