/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthRegister201UserPhone } from './postAuthRegister201UserPhone';
import type { PostAuthRegister201UserProfileImage } from './postAuthRegister201UserProfileImage';

export type PostAuthRegister201User = {
  id?: string;
  email?: string;
  phone?: PostAuthRegister201UserPhone;
  username?: string;
  profile_image?: PostAuthRegister201UserProfileImage;
  currency?: string;
  language?: string;
  email_verified?: boolean;
  created_at?: string;
  updated_at?: string;
};
