/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthLogin200UserPhone } from './postAuthLogin200UserPhone';
import type { PostAuthLogin200UserProfileImage } from './postAuthLogin200UserProfileImage';

export type PostAuthLogin200User = {
  id?: string;
  email?: string;
  phone?: PostAuthLogin200UserPhone;
  username?: string;
  profile_image?: PostAuthLogin200UserProfileImage;
  currency?: string;
  language?: string;
  email_verified?: boolean;
  created_at?: string;
  updated_at?: string;
};
