/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export type PostAuthRegisterBody = {
  /** @maxLength 255 */
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /**
   * @minLength 3
   * @maxLength 30
   * @pattern ^[a-zA-Z0-9_]{3,30}$
   */
  username: string;
  /**
   * @minLength 5
   * @maxLength 20
   */
  phone?: string;
  /** @maxLength 255 */
  device_name?: string;
};
