/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthRefresh200UserPhone } from './postAuthRefresh200UserPhone';
import type { PostAuthRefresh200UserProfileImage } from './postAuthRefresh200UserProfileImage';

export type PostAuthRefresh200User = {
  id?: string;
  email?: string;
  phone?: PostAuthRefresh200UserPhone;
  username?: string;
  profile_image?: PostAuthRefresh200UserProfileImage;
  currency?: string;
  language?: string;
  email_verified?: boolean;
  created_at?: string;
  updated_at?: string;
};
