/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthRefresh200TokenType } from './postAuthRefresh200TokenType';
import type { PostAuthRefresh200User } from './postAuthRefresh200User';

export type PostAuthRefresh200 = {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  token_type?: PostAuthRefresh200TokenType;
  user?: PostAuthRefresh200User;
};
