/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */

export type PostAuthLogin200TokenType = typeof PostAuthLogin200TokenType[keyof typeof PostAuthLogin200TokenType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostAuthLogin200TokenType = {
  Bearer: 'Bearer',
} as const;
