/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { PostAuthLogin200TokenType } from './postAuthLogin200TokenType';
import type { PostAuthLogin200User } from './postAuthLogin200User';

export type PostAuthLogin200 = {
  access_token?: string;
  refresh_token?: string;
  expires_in?: number;
  token_type?: PostAuthLogin200TokenType;
  user?: PostAuthLogin200User;
};
