/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { SessionDeviceName } from './sessionDeviceName';
import type { SessionIpAddress } from './sessionIpAddress';
import type { SessionUserAgent } from './sessionUserAgent';

export interface Session {
  id?: string;
  user_id?: string;
  device_name?: SessionDeviceName;
  ip_address?: SessionIpAddress;
  user_agent?: SessionUserAgent;
  expires_at?: string;
  created_at?: string;
}
