/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Tally API
 * Personal and shared expense tracker API — auth, ledgers, groups, and more.
 * OpenAPI spec version: 0.1.0
 */
import type { UserPhone } from './userPhone';
import type { UserProfileImage } from './userProfileImage';

export interface User {
  id?: string;
  email?: string;
  phone?: UserPhone;
  username?: string;
  display_name?: string;
  profile_image?: UserProfileImage;
  currency?: string;
  language?: string;
  monthly_budget?: number | null;
  email_verified?: boolean;
  created_at?: string;
  updated_at?: string;
}
